- alias: Выключатель света в кабинете Андрея
  use_blueprint:
    path: domovoy/wall-switch.yaml
    input:
      wall_switch: a9b348fb91b46bd69b18a04ad670c375
      light_group: light.light_group_andrey
